### ISSUE TITLE
Error accessing page on computer

### ISSUE THREAD

**Issue by NightWingMistHawk** [king-2349/wiiphone#1]
So, as I said in the reddit post (https://www.reddit.com/r/DolphinEmulator/comments/v24mvk/i_created_a_service_to_let_you_use_your_phone_as/), I was able to access the actual wiimote page on my computer. However, whenever I access the page on my computer, the server crashes with the following error:

node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, stat './WiiPhoneUI/build/logo192.png'
    at Object.statSync (node:fs:1551:3)
    at Server.<anonymous> (file:///C:/Users/natha/OneDrive/Desktop/wiiphone-main/index.js:258:20)
    at Server.emit (node:events:527:28)
    at parserOnIncoming (node:_http_server:956:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: './WiiPhoneUI/build/logo192.png'

Also unable to access the webpage on my phone at all (used DuckDuckGo, Safari and Chrome and all three failed to find the server) so maybe this has something to do with that?

**Comment by king-2349** [comment]
Hello. I deleted some logos from the project and forgot to remove the references to them, so it was trying to load data that didn't exist. I have updated the code to correct this error, and have also added code to the server to display the correct address to input on your phone.
If you redownload the project now the fix should take affect

**Comment by king-2349** [comment]
You will also have to run the "npm install" command again
